import { createHash } from "node:crypto"
import { readFile } from "node:fs/promises"

const root = new URL("../", import.meta.url)
const manifest = JSON.parse(
  await readFile(new URL("vendor/manifest.json", root), "utf8"),
)

for (const [filename, expectedHash] of Object.entries(manifest.files)) {
  const contents = await readFile(new URL(`vendor/${filename}`, root))
  const actualHash = createHash("sha256").update(contents).digest("hex")
  if (actualHash !== expectedHash) {
    throw new Error(
      `${filename} has SHA-256 ${actualHash}; expected ${expectedHash}`,
    )
  }
}

const wasm = await readFile(new URL("vendor/manifold.wasm", root))
const expectedEmbeddedModule = `// Generated by scripts/generate-embedded-wasm.mjs. Do not edit.\nexport default ${JSON.stringify(wasm.toString("base64"))}\n`
const embeddedModule = await readFile(
  new URL("vendor/manifold.wasm.base64.js", root),
  "utf8",
)
if (embeddedModule !== expectedEmbeddedModule) {
  throw new Error(
    "vendor/manifold.wasm.base64.js is stale; run npm run generate:embedded-wasm",
  )
}

console.log(`Verified vendored manifold-3d@${manifest.version}`)
